-- 코드를 입력하세요
# SELECT * FROM ONLINE_SALE
# GROUP BY USER_ID,PRODUCT_ID
# ORDER BY USER_ID,PRODUCT_ID

WITH TABLE1 AS(
    SELECT USER_ID,PRODUCT_ID,COUNT(SALES_AMOUNT) AS AMOUNT FROM ONLINE_SALE
    GROUP BY USER_ID,PRODUCT_ID
    ORDER BY COUNT(SALES_AMOUNT) DESC
)
SELECT USER_ID,PRODUCT_ID FROM TABLE1
WHERE AMOUNT >=2
ORDER BY USER_ID ASC, PRODUCT_ID DESC


# SELECT * FROM ONLINE_SALE
# ORDER BY USER_ID DESC