-- 코드를 입력하세요
SELECT BOOK_ID,AUTHOR.AUTHOR_NAME,SUBSTRING(BOOK.PUBLISHED_DATE,1,10) FROM BOOK
LEFT JOIN AUTHOR ON 
BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE BOOK.CATEGORY = '경제'
ORDER BY BOOK.PUBLISHED_DATE ASC